// Generated by https://quicktype.io

import { IApiResource } from './IApiResource';

export interface IPokemonSpecy {
  base_happiness: number;
  capture_rate: number;
  color: IApiResource;
  egg_groups: IApiResource[];
  evolution_chain: EvolutionChain;
  evolves_from_species: null;
  flavor_text_entries: FlavorTextEntry[];
  form_descriptions: string[];
  forms_switchable: boolean;
  gender_rate: number;
  genera: Genus[];
  generation: IApiResource;
  growth_rate: IApiResource;
  habitat: IApiResource;
  has_gender_differences: boolean;
  hatch_counter: number;
  id: number;
  is_baby: boolean;
  is_legendary: boolean;
  is_mythical: boolean;
  name: string;
  names: Name[];
  order: number;
  pal_park_encounters: PalParkEncounter[];
  pokedex_numbers: PokedexNumber[];
  shape: IApiResource;
  varieties: Variety[];
}

export interface EvolutionChain {
  url: string;
}

export interface FlavorTextEntry {
  flavor_text: string;
  language: IApiResource;
  version: IApiResource;
}

export interface Genus {
  genus: string;
  language: IApiResource;
}

export interface Name {
  language: IApiResource;
  name: string;
}

export interface PalParkEncounter {
  area: IApiResource;
  base_score: number;
  rate: number;
}

export interface PokedexNumber {
  entry_number: number;
  pokedex: IApiResource;
}

export interface Variety {
  is_default: boolean;
  pokemon: IApiResource;
}
